title: Configuration
data:
  logo: logos/logo-brand.svg
  header_buttons:
    -
      button_label: 'Sign in'
      link_type: url
      target_blank: false
      url: '#'
      button_type: text
    -
      button_label: 'Get started'
      link_type: url
      target_blank: false
      url: '#'
      button_type: primary
  error_404_entry: 069f6c1b-b5f6-41bf-804f-b3ce7085ebba
  newsletter: false
  about: 'A one-person premium web development service with flat rate plans and a butter-smooth process.'
  copyright_since: 2022
  copyright_text: 'Remarkable.dev, LLC. All rights reserved.'
