title: Configuration
data:
  logo: logos/logo-brand.svg
  header_buttons:
    -
      id: 1wCZptZ7
      button_label: 'Sign in'
      link_type: url
      target_blank: false
      url: '#'
      button_type: text
      button:
        label: 'Sign in'
        show_controls: null
        link_type: url
        target_blank: false
        entry: null
        url: /
        email: null
        tel: null
        asset: null
        code: null
        button_type: text
    -
      id: k0sBnlT1
      button_label: 'Get started'
      link_type: url
      target_blank: false
      url: '#'
      button_type: primary
      button:
        label: 'Get started'
        show_controls: null
        link_type: url
        target_blank: false
        entry: null
        url: /
        email: null
        tel: null
        asset: null
        code: null
        button_type: primary
  newsletter: false
  about: 'A one-person premium web development service with flat rate plans and a butter-smooth process.'
  copyright_text: 'Remarkable.dev, LLC. All rights reserved.'
