sections:
  general:
    display: General
    fields:
      -
        handle: logo
        field: common.image
        config:
          display: Logo
  header:
    display: Header
    fields:
      -
        import: buttons
        prefix: header_
  footer:
    display: Footer
    fields:
      -
        handle: newsletter
        field:
          default: false
          display: Newsletter
          type: toggle
          icon: toggle
          listable: hidden
      -
        handle: newsletter_title
        field:
          input_type: text
          antlers: false
          display: 'Newsletter title'
          type: text
          icon: text
          listable: hidden
          if:
            newsletter: 'equals true'
      -
        handle: newsletter_button_title
        field:
          input_type: text
          antlers: false
          default: Subscribe
          display: 'Button Title'
          type: text
          icon: text
          listable: hidden
          width: 50
          if:
            newsletter: 'equals true'
      -
        handle: about
        field: common.text_plain
        config:
          display: About
      -
        handle: copyright_text
        field:
          input_type: text
          antlers: false
          default: 'All rights reserved.'
          display: 'Copyright text'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          instructions: 'Company name, registration, address, etc.'
          width: 50
